---

# Set up docker to use as drive for nomad
- name: Installation methods
  block:
    - name: Install using the repository
      ansible.builtin.yum:
        name: yum-utils
        state: present

    - name: Add Docker repo
      shell: 'curl -L "https://download.docker.com/linux/centos/docker-ce.repo" -o /etc/yum.repos.d/docker-ce.repo'

- name: Install Docker Engine
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io

- name: Start Docker daemon
  ansible.builtin.systemd:
    state: started
    name: docker
    enabled: yes